### ISSUE TITLE
log filled up with permissions changes not being done

### ISSUE THREAD

**Issue by CraziFuzzy** [stuckless/sagetv-dockers#5]
The docker log is getting filled up with rather useless reports of files whose ownership is not being set because it is already set.  This is because chown is being run with -v, which is fine, because we do want to see if a file is not being set for some reason, but I'm wondering if we can
`chown -Rv sagetv:sagetv /var/media | grep -v "retained as sagetv:users"`
and so on.  The docker log in unRAID seems to be size limited, so actions at the beginning of the run are flushed out currently.

**Comment by stuckless** [comment]
That's a great idea... I'll update the script accordingly.
