### ISSUE TITLE
Start Scripts fail to start without internet access.

### ISSUE THREAD

**Issue by stanger89** [stuckless/sagetv-dockers#7]
After attempting to restart the docker with the internet connection down, I found that the startup scripts fail.  It's likely they'll fail in any situation where bintray is unreachable.

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10-adduser...
*** Running /etc/my_init.d/20-upgrade-sagetv...
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
SageTV Home: /opt/sagetv/server
Backing up Wiz.bin, Sage.properties and Sage.jar before upgrade
'Wiz.bin' -> 'backups/20161031_165835/Wiz.bin'
'Sage.properties' -> 'backups/20161031_165835/Sage.properties'
'Sage.jar' -> 'backups/20161031_165835/Sage.jar'
Installing/Upgrading SageTV to
--2016-10-31 16:58:35-- https://bintray.com/artifact/download/opensagetv/sagetv/sagetv//sagetv-server__amd64.tar.gz
Resolving bintray.com (bintray.com)... 10.0.0.1, 10.0.0.1
Connecting to bintray.com (bintray.com)|10.0.0.1|:443... failed: Network is unreachable.
Connecting to bintray.com (bintray.com)|10.0.0.1|:443... failed: Network is unreachable.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to download Server!!! URL: https://bintray.com/artifact/download/opensagetv/sagetv/sagetv//sagetv-server__amd64.tar.gz
*** /etc/my_init.d/20-upgrade-sagetv failed with status 2

*** Killing all processes...

**Comment by CraziFuzzy** [comment]
Made a quick fix and submitted a pull request #8 .  Hopefully this works once it's implemented and a new build released (I know it won't help $stanger89 right now).

**Comment by stuckless** [comment]
Merged
